---
-
  bg: cio
    - 'bretts.jgp'
    - 'fronthouse.jpg'
    - 'hike_2.jpeg'
    - 'mt_wash_from_bwoods.jpg'
    - 'hike.jpeg'
    - 'house.jpeg'
    - 'mt_washington.jpg'
    - 'summit_sign'
    - 'tubing.jpg'
    - 'tucks_2.jpeg'
    - 'tucks_3.jpg'
    - 'tucks.jpg'
    - 'ullr.jpeg'
